name: django-local-postgres-docker

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
